config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link          http://cakephp.org CakePHP(tm) Project
 * @license       http://www.opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'So', 'action' => 'index', 'home']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks(DashedRoute::class);
});

/**
 * Load all plugin routes.  See the Plugin documentation on
 * how to customize the loading of plugin routes.
 */
Plugin::routes();

src/Model/Table/PersonsTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Persons Model
 *
 * @property \Cake\ORM\Association\BelongsTo $Categories
 *
 * @method \App\Model\Entity\Person get($primaryKey, $options = [])
 * @method \App\Model\Entity\Person newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\Person[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Person|bool save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Person patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Person[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\Person findOrCreate($search, callable $callback = null)
 */
class PersonsTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->table('persons');
        $this->displayField('name');
        $this->primaryKey('cpf');

        $this->belongsTo('Categories', [
            'foreignKey' => 'category_id',
            'joinType' => 'INNER'
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->allowEmpty('cpf', 'create')
            ->notEmpty('cpf', 'CPF can\'t be empty.')
            ->add('cpf', 'cpf', ['rule' => 'validateUnique', 'provider' => 'table', 'message' => 'This CPF already registered.'])
            ->add('cpf', 'cpf-length', ['rule' => ['minLength', 11], 'message' => 'CPF must be 11 characters long.']);

        $validator
            ->requirePresence('name', 'create')
            ->notEmpty('name', 'Name can\'t be empty.')
            ->add('name', 'name-length', ['rule' => ['minLength', 3], 'message' => 'Name require minimum 3 characters.']);

        $validator
            ->email('email')
            ->requirePresence('email', 'create')
            ->notEmpty('email', 'Email can\'t be empty.')
            ->add('email', 'email-valid', ['rule' => 'email', 'message' => 'Valid email required.'])
            ->add('email', 'email', ['rule' => 'validateUnique', 'provider' => 'table', 'message' => 'This Email already registered.']);

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->isUnique(['email']));
        $rules->add($rules->isUnique(['cpf']));
        $rules->add($rules->existsIn(['category_id'], 'Categories'));

        return $rules;
    }
}

src/Controller/ExecutorsController.php
<?php

namespace App\Controller;

use Cake\Core\Configure;
use Cake\Network\Exception\ForbiddenException;
use Cake\Network\Exception\NotFoundException;
use Cake\View\Exception\MissingTemplateException;

/**
 * Executors Controller
 *
 * @property \App\Model\Table\PersonsTable $Persons
 */
class ExecutorsController extends AppController
{
    public function initialize()
    {
        parent::initialize();
        $this->set('title', 'Executors');
    }

    public function index()
    {
        $where = ['category_id' => 1];
        $s = null;

        if (isset($_GET['s']) ) {
            $s = $_GET['s'];
            $where['name LIKE'] = '%' . $s . '%';
        }

        $query = $this->loadModel('Persons')->find('all')->where($where);

        $executors = $this->paginate($query);

        $this->set(compact('executors', 's'));
    }

    public function view($id = null)
    {
        $executor = $this->loadModel('Persons')->get($id, [
            'contain' => ['Categories']
        ]);

        $soList = $this->loadModel('So')->find('all')->where([
            'executor_id =' => $executor->cpf
        ])->toArray();

        $this->set(compact('executor', 'soList'));
    }

    public function add()
    {
        $executor = $this->loadModel('Persons')->newEntity();

        if ($this->request->is('post')) {
            $executor = $this->loadModel('Persons')->patchEntity($executor, $this->request->data);
            $saved = $this->loadModel('Persons')->save($executor);
            
            if ($saved) {
                $this->Flash->success(__('The executor has been saved.'));
                return $this->redirect(['action' => 'view/' . $saved->cpf]);
            } 
            else {
                foreach ($executor->errors() as $error) {
                    foreach ($error as $msg) {
                        $this->Flash->error($msg);
                    }
                }

                $this->set(compact('executor'));
                return;
            }
        }

        $this->set(compact('executor'));
    }

    public function edit($id = null)
    {
        $executor = $this->loadModel('Persons')->get($id);

        if ($this->request->is(['patch', 'post', 'put'])) {

            $executor = $this->loadModel('Persons')->patchEntity($executor, $this->request->data);

            if ($this->loadModel('Persons')->save($executor)) {
                $this->Flash->success(__('The executor has been saved.'));

                return $this->redirect(['action' => 'view/' . $executor->cpf]);
            } 
            else {
                foreach ($executor->errors() as $error) {
                    foreach ($error as $msg) {
                        $this->Flash->error($msg);
                    }
                }

                $this->set(compact('executor'));
                return;
            }
        }

        $this->set(compact('executor'));
    }

    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $executor = $this->loadModel('Persons')->get($id);

        $soQuery = $this->loadModel('So')->find('all')->where([
            'executor_id =' => $executor->cpf
        ]);

        if (count($soQuery->toArray()) > 0) {
            $this->Flash->error(__('The executor could not be deleted. He\'s related be one or more Services Orders.'));
            return $this->redirect(['action' => 'view/' . $executor->cpf]);
        }


        if ($this->loadModel('Persons')->delete($executor)) {
            $this->Flash->success(__('The executor has been deleted.'));
        } 
        else {
            $this->Flash->error(__('The executor could not be deleted. Please, try again.'));
        }

        return $this->redirect(['action' => 'index']);
    }
}

src/Template/Executors/add.ctp
<h3><?php echo __('Add Executor') ?></h3>

<hr />
<?php echo $this->Form->create('Executors', array('type' => 'post', 'class' => 'edit-form')); ?>

<div class="row">
    <div class="col-md-3">
        <label for="cpf"><?php echo __('CPF') ?></label>
        <div class="form-group">
            <input id="cpf" class="form-control" type="text" name="cpf" maxlength="11" placeholder="CPF" value="<?php echo $executor->cpf ?>" />
        </div>
    </div>

    <div class="col-md-3">
        <label for="email"><?php echo __('Email') ?></label>
        <div class="form-group">
            <input id="email" class="form-control" type="text" name="email" placeholder="Email" value="<?php echo $executor->email ?>" />
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-9">
        <label for="name"><?php echo __('Name') ?></label>
        <div class="form-group">
            <input id="name" class="form-control" type="text" name="name" placeholder="Name" value="<?php echo $executor->name ?>" />
        </div>
    </div>
</div>

<input type="hidden" name="category_id" value="1">

<button type="submit" class="btn btn-primary"><?php echo __('Submit') ?></button>

<div class="clearfix"></div>

<?php echo $this->Form->end() ?>

src/Template/Executors/edit.ctp
<h3><?php echo __('Edit Executor') ?></h3>

<hr />
<?php echo $this->Form->create('Executors', array('type' => 'post', 'class' => 'edit-form')); ?>

<div class="row">
    <div class="col-md-3">
        <label for="cpf"><?php echo __('CPF') ?></label>
        <div class="form-group">
            <input id="cpf" class="form-control" type="text" name="cpf" maxlength="11" placeholder="CPF" value="<?php echo $executor->cpf ?>" />
        </div>
    </div>

    <div class="col-md-3">
        <label for="email"><?php echo __('Email') ?></label>
        <div class="form-group">
            <input id="email" class="form-control" type="text" name="email" placeholder="Email" value="<?php echo $executor->email ?>" />
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-9">
        <label for="name"><?php echo __('Name') ?></label>
        <div class="form-group">
            <input id="name" class="form-control" type="text" name="name" placeholder="Name" value="<?php echo $executor->name ?>" />
        </div>
    </div>
</div>

<input type="hidden" name="category_id" value="1">

<button type="submit" class="btn btn-primary"><?php echo __('Submit') ?></button>

<div class="clearfix"></div>

<?php echo $this->Form->end() ?>

src/Template/Executors/index.ctp
<h3><?php echo __('Executors') ?></h3>

<hr />

<?php if (count($executors->toArray()) > 0) :  ?>

<?php echo $this->element('simple-search-form', [
    'controller' => 'Executors',
    'placeholder' => 'Search by executor name',
    's' => $s,
    'items' => $executors
]) ?>

    
<table class="table table-hover table-striped">
    <thead>
        <tr>
            <th scope="col" class="text-uppercase"><?php echo $this->Paginator->sort('cpf') ?></th>
            <th scope="col"><?php echo $this->Paginator->sort('name') ?></th>
            <th scope="col"><?php echo $this->Paginator->sort('email') ?></th>
            <th scope="col" class="actions"><?php echo __('Actions') ?></th>
        </tr>
    </thead>

    <tbody>
        <?php foreach ($executors as $executor): ?>
        <tr>
            <td><?php echo h($executor->cpf) ?></td>
            <td><?php echo h($executor->name) ?></td>
            <td><?php echo h($executor->email) ?></td>
            <td class="actions">
                <?php echo $this->Html->link(__(''), ['action' => 'view', $executor->cpf, 'controller' => 'Executors'], ['class' => 'glyphicon glyphicon-eye-open']) ?>
                <?php echo $this->Html->link(__(''), ['action' => 'edit', $executor->cpf, 'controller' => 'Executors'], ['class' => 'glyphicon glyphicon-pencil']) ?>
                <?php echo $this->Form->postLink(
                    __(''), 
                    ['action' => 'delete', $executor->cpf, 'controller' => 'Executors'], 
                    ['confirm' => __('Are you sure you want to delete # {0}?', $executor->cpf), 
                        'class' => 'glyphicon glyphicon-trash']
                ) ?>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<?php echo $this->element('paginator') ?>

<?php else : ?>
<p><?php echo __('You do not have Executors to list') ?>. 
<?php echo $this->Html->link(__('Add Executor'), ['controller' => 'Executors', 'action' => 'add']) ?></p>
<?php endif ?>

src/Template/Executors/view.ctp
<h3 class="pull-left"><?php echo h($executor->name) ?></h3>

<?php 
echo $this->Form->postLink( 
    __('Delete'), 
    ['action' => 'delete', $executor->cpf],  
    ['confirm' => __('Are you sure you want to delete # {0}?', $executor->cpf), 
        'class' => 'btn btn-danger pull-right']);
?>

<div class="clearfix"></div>

<hr />
    
<table class="vertical-table">
    <tr>
        <th scope="row"><?php echo __('CPF') ?></th>
        <td><?php echo h($executor->cpf) ?></td>
    </tr>
    <tr>
        <th scope="row"><?php echo __('Name') ?></th>
        <td><?php echo h($executor->name) ?></td>
    </tr>
    <tr>
        <th scope="row"><?php echo __('Email') ?></th>
        <td><?php echo h($executor->email) ?></td>
    </tr>
    <tr>
        <th scope="row"><?php echo __('Category') ?></th>
        <td><?php echo $executor->has('category') ? h($executor->category->description) : '' ?></td>
    </tr>
</table>

<h4><?php echo __('Services Orders') ?></h4>

<div class="row">
    <div class="col-md-9">
        <?php if(count($soList) > 0) : ?>
        <?php foreach($soList as $so) : ?>
        <?php 
        echo $this->Html->link(
            'Id: ' . $so->id . ' - Date: ' . date_format($so->date, 'm/d/Y'), 
            ['controller' => 'So', 'action' => 'view', $so->id], 
            ['class' => 'label label-default']);
        ?>
        <?php endforeach ?>
        <?php else : ?>
        <p><?php echo __('This executor is\'nt related any Service Order') ?>.</p>
        <?php endif ?>
    </div>
</div>